openapi: 3.2.0
info:
  title: Qdrant Indexes API
  description: API description for Qdrant vector search engine.
  contact:
    email: andrey@vasnetsov.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: master
servers:
- url: '{protocol}://{hostname}:{port}'
  variables:
    protocol:
      enum:
      - http
      - https
      default: http
    hostname:
      default: localhost
    port:
      default: '6333'
security:
- api-key: []
- bearerAuth: []
- {}
tags:
- name: Indexes
  description: Indexes for payloads associated with points.
paths:
  /collections/{collection_name}/index:
    put:
      tags:
      - Indexes
      summary: Create index for field in collection
      operationId: create_field_index
      parameters:
      - name: collection_name
        in: path
        description: Name of the collection
        required: true
        schema:
          type: string
      - name: wait
        in: query
        description: If true, wait for changes to actually happen
        required: false
        schema:
          type: boolean
      - name: ordering
        in: query
        description: define ordering guarantees for the operation
        required: false
        schema:
          $ref: '#/components/schemas/WriteOrdering'
      - name: timeout
        in: query
        description: Timeout for the operation
        required: false
        schema:
          type: integer
          minimum: 1
      requestBody:
        description: Field name
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFieldIndex'
      responses:
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        4XX:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  usage:
                    default: null
                    anyOf:
                    - $ref: '#/components/schemas/Usage'
                    - {}
                  time:
                    type: number
                    format: float
                    description: Time spent to process this request
                    example: 0.002
                  status:
                    type: string
                    example: ok
                  result:
                    $ref: '#/components/schemas/UpdateResult'
  /collections/{collection_name}/index/{field_name}:
    delete:
      tags:
      - Indexes
      summary: Delete index for field in collection
      description: Delete field index for collection
      operationId: delete_field_index
      parameters:
      - name: collection_name
        in: path
        description: Name of the collection
        required: true
        schema:
          type: string
      - name: field_name
        in: path
        description: Name of the field where to delete the index
        required: true
        schema:
          type: string
      - name: wait
        in: query
        description: If true, wait for changes to actually happen
        required: false
        schema:
          type: boolean
      - name: ordering
        in: query
        description: define ordering guarantees for the operation
        required: false
        schema:
          $ref: '#/components/schemas/WriteOrdering'
      - name: timeout
        in: query
        description: Timeout for the operation
        required: false
        schema:
          type: integer
          minimum: 1
      responses:
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        4XX:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  usage:
                    default: null
                    anyOf:
                    - $ref: '#/components/schemas/Usage'
                    - {}
                  time:
                    type: number
                    format: float
                    description: Time spent to process this request
                    example: 0.002
                  status:
                    type: string
                    example: ok
                  result:
                    $ref: '#/components/schemas/UpdateResult'
components:
  schemas:
    PayloadSchemaType:
      description: All possible names of payload types
      type: string
      enum:
      - keyword
      - integer
      - float
      - geo
      - text
      - bool
      - datetime
      - uuid
    Usage:
      description: Usage of the hardware resources, spent to process the request
      type: object
      properties:
        hardware:
          anyOf:
          - $ref: '#/components/schemas/HardwareUsage'
          - {}
        inference:
          anyOf:
          - $ref: '#/components/schemas/InferenceUsage'
          - {}
    PayloadSchemaParams:
      description: Payload type with parameters
      anyOf:
      - $ref: '#/components/schemas/KeywordIndexParams'
      - $ref: '#/components/schemas/IntegerIndexParams'
      - $ref: '#/components/schemas/FloatIndexParams'
      - $ref: '#/components/schemas/GeoIndexParams'
      - $ref: '#/components/schemas/TextIndexParams'
      - $ref: '#/components/schemas/BoolIndexParams'
      - $ref: '#/components/schemas/DatetimeIndexParams'
      - $ref: '#/components/schemas/UuidIndexParams'
    UpdateStatus:
      description: '`Acknowledged` - Request is saved to WAL and will be process in a queue. `Completed` - Request is completed, changes are actual. `WaitTimeout` - Request is waiting for timeout.'
      type: string
      enum:
      - acknowledged
      - completed
      - wait_timeout
    StopwordsSet:
      type: object
      properties:
        languages:
          description: Set of languages to use for stopwords. Multiple pre-defined lists of stopwords can be combined.
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Language'
          uniqueItems: true
        custom:
          description: Custom stopwords set. Will be merged with the languages set.
          type:
          - array
          - 'null'
          items:
            type: string
          uniqueItems: true
    IntegerIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/IntegerIndexType'
        lookup:
          description: If true - support direct lookups. Default is true.
          type:
          - boolean
          - 'null'
        range:
          description: If true - support ranges filters. Default is true.
          type:
          - boolean
          - 'null'
        is_principal:
          description: If true - use this key to organize storage of the collection data. This option assumes that this key will be used in majority of filtered requests. Default is false.
          type:
          - boolean
          - 'null'
        on_disk:
          description: 'If true, store the index on disk. Default: false. Default is false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    PayloadFieldSchema:
      anyOf:
      - $ref: '#/components/schemas/PayloadSchemaType'
      - $ref: '#/components/schemas/PayloadSchemaParams'
    SnowballLanguage:
      description: Languages supported by snowball stemmer.
      type: string
      enum:
      - arabic
      - armenian
      - danish
      - dutch
      - english
      - finnish
      - french
      - german
      - greek
      - hungarian
      - italian
      - norwegian
      - portuguese
      - romanian
      - russian
      - spanish
      - swedish
      - tamil
      - turkish
    DatetimeIndexType:
      type: string
      enum:
      - datetime
    GeoIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/GeoIndexType'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    StopwordsInterface:
      anyOf:
      - $ref: '#/components/schemas/Language'
      - $ref: '#/components/schemas/StopwordsSet'
    HardwareUsage:
      description: Usage of the hardware resources, spent to process the request
      type: object
      required:
      - cpu
      - payload_index_io_read
      - payload_index_io_write
      - payload_io_read
      - payload_io_write
      - vector_io_read
      - vector_io_write
      properties:
        cpu:
          type: integer
          format: uint
          minimum: 0
        payload_io_read:
          type: integer
          format: uint
          minimum: 0
        payload_io_write:
          type: integer
          format: uint
          minimum: 0
        payload_index_io_read:
          type: integer
          format: uint
          minimum: 0
        payload_index_io_write:
          type: integer
          format: uint
          minimum: 0
        vector_io_read:
          type: integer
          format: uint
          minimum: 0
        vector_io_write:
          type: integer
          format: uint
          minimum: 0
    UuidIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/UuidIndexType'
        is_tenant:
          description: If true - used for tenant optimization.
          type:
          - boolean
          - 'null'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    FloatIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/FloatIndexType'
        is_principal:
          description: If true - use this key to organize storage of the collection data. This option assumes that this key will be used in majority of filtered requests.
          type:
          - boolean
          - 'null'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    FloatIndexType:
      type: string
      enum:
      - float
    BoolIndexType:
      type: string
      enum:
      - bool
    UuidIndexType:
      type: string
      enum:
      - uuid
    GeoIndexType:
      type: string
      enum:
      - geo
    WriteOrdering:
      description: 'Defines write ordering guarantees for collection operations


        * `weak` - write operations may be reordered, works faster, default


        * `medium` - write operations go through dynamically selected leader, may be inconsistent for a short period of time in case of leader change


        * `strong` - Write operations go through the permanent leader, consistent, but may be unavailable if leader is down'
      type: string
      enum:
      - weak
      - medium
      - strong
    CreateFieldIndex:
      type: object
      required:
      - field_name
      properties:
        field_name:
          type: string
        field_schema:
          anyOf:
          - $ref: '#/components/schemas/PayloadFieldSchema'
          - {}
    KeywordIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/KeywordIndexType'
        is_tenant:
          description: 'If true - used for tenant optimization. Default: false.'
          type:
          - boolean
          - 'null'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    InferenceUsage:
      type: object
      required:
      - models
      properties:
        models:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ModelUsage'
    UpdateResult:
      type: object
      required:
      - status
      properties:
        operation_id:
          description: Sequential number of the operation
          type:
          - integer
          - 'null'
          format: uint64
          minimum: 0
        status:
          $ref: '#/components/schemas/UpdateStatus'
    DatetimeIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/DatetimeIndexType'
        is_principal:
          description: If true - use this key to organize storage of the collection data. This option assumes that this key will be used in majority of filtered requests.
          type:
          - boolean
          - 'null'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    Language:
      type: string
      enum:
      - arabic
      - azerbaijani
      - basque
      - bengali
      - catalan
      - chinese
      - danish
      - dutch
      - english
      - finnish
      - french
      - german
      - greek
      - hebrew
      - hinglish
      - hungarian
      - indonesian
      - italian
      - japanese
      - kazakh
      - nepali
      - norwegian
      - portuguese
      - romanian
      - russian
      - slovene
      - spanish
      - swedish
      - tajik
      - turkish
    StemmingAlgorithm:
      description: Different stemming algorithms with their configs.
      anyOf:
      - $ref: '#/components/schemas/SnowballParams'
    SnowballParams:
      type: object
      required:
      - language
      - type
      properties:
        type:
          $ref: '#/components/schemas/Snowball'
        language:
          $ref: '#/components/schemas/SnowballLanguage'
    KeywordIndexType:
      type: string
      enum:
      - keyword
    TextIndexType:
      type: string
      enum:
      - text
    IntegerIndexType:
      type: string
      enum:
      - integer
    ErrorResponse:
      type: object
      properties:
        time:
          type: number
          format: float
          description: Time spent to process this request
        status:
          type: object
          properties:
            error:
              type: string
              description: Description of the occurred error.
        result:
          type:
          - object
          - 'null'
    BoolIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/BoolIndexType'
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    TextIndexParams:
      type: object
      required:
      - type
      properties:
        type:
          $ref: '#/components/schemas/TextIndexType'
        tokenizer:
          $ref: '#/components/schemas/TokenizerType'
        min_token_len:
          description: Minimum characters to be tokenized.
          type:
          - integer
          - 'null'
          format: uint
          minimum: 0
        max_token_len:
          description: Maximum characters to be tokenized.
          type:
          - integer
          - 'null'
          format: uint
          minimum: 0
        lowercase:
          description: 'If true, lowercase all tokens. Default: true.'
          type:
          - boolean
          - 'null'
        ascii_folding:
          description: 'If true, normalize tokens by folding accented characters to ASCII (e.g., "ação" -> "acao"). Default: false.'
          type:
          - boolean
          - 'null'
        phrase_matching:
          description: 'If true, support phrase matching. Default: false.'
          type:
          - boolean
          - 'null'
        stopwords:
          description: Ignore this set of tokens. Can select from predefined languages and/or provide a custom set.
          anyOf:
          - $ref: '#/components/schemas/StopwordsInterface'
          - {}
        on_disk:
          description: 'If true, store the index on disk. Default: false.'
          type:
          - boolean
          - 'null'
        stemmer:
          description: 'Algorithm for stemming. Default: disabled.'
          anyOf:
          - $ref: '#/components/schemas/StemmingAlgorithm'
          - {}
        enable_hnsw:
          description: 'Enable HNSW graph building for this payload field. If true, builds additional HNSW links (Need payload_m > 0). Default: true.'
          type:
          - boolean
          - 'null'
    Snowball:
      type: string
      enum:
      - snowball
    TokenizerType:
      type: string
      enum:
      - prefix
      - whitespace
      - word
      - multilingual
    ModelUsage:
      type: object
      required:
      - tokens
      properties:
        tokens:
          type: integer
          format: uint64
          minimum: 0
  securitySchemes:
    api-key:
      type: apiKey
      in: header
      name: api-key
      description: Authorization key, either read-write or read-only
    bearerAuth:
      type: http
      scheme: bearer
externalDocs:
  description: Find out more about Qdrant applications and demo
  url: https://qdrant.tech/documentation/
